task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls", namespace="todo")),

]

todo/urls.py
from django.urls import path

from todo.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    task_toggle_assign,

    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "tasks/<int:pk>/toggle-assign/",
        task_toggle_assign,
        name="task-toggle-assign",
    ),

    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo"

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self) -> str:
        return str(self.name)


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, default=None, blank=True)
    status = models.BooleanField(default=False)
    tag = models.ManyToManyField(to=Tag, related_name="tasks")

    class Meta:
        ordering = ["-status"]

    def __str__(self) -> str:
        return str(self.content)

todo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")


def task_toggle_assign(request, pk):
    task = Task.objects.get(id=pk)
    if task.status is False:
        task.status = True
    else:
        task.status = False
    task.save()
    return redirect("todo:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
{#    {% load static %}#}
{#    <link rel="stylesheet" href="{% static 'css/styles.css' %}">#}
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}

            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
{#  <li class="list-group-item"><a href="{% url 'taxi:car-list' %}">All cars</a></li>#}
{#  <li class="list-group-item"><a href="{% url 'taxi:manufacturer-list' %}">All manufacturers</a></li>#}
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url "todo:tag-list"%}">Cancel</a>
  </form>

{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div >
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
  </div>

{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}

<h1>Tag list</h1>

  <div class="d-flex justify-content-between align-items-center mb-3">
    <h2 class="mb-0"></h2>
    <a href="{% url 'todo:tag-create' %}" class="btn btn-secondary ml-auto">Add</a>
  </div>
  <table class="table">
  <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
  </tr>
  {% for tag in tag_list %}
    <tr>
    <td>{{ tag.name }}</td>
    <td><a href="{% url 'todo:tag-update' pk=tag.id %}" class="btn btn-secondary link-to-page">Update</a></td>
    <td><a href="{% url 'todo:tag-delete' pk=tag.id %}" class="btn btn-secondary link-to-page">Delete</a></td>
    </tr>

  {% endfor %}

{% endblock %}
  </table>

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url "todo:task-list"%}">Cancel</a>
  </form>

{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div >
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
  </div>

{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Task list</h1>

  <a href="{% url 'todo:task-create' %}" class="btn btn-primary link-to-page">Create</a>

  <table class="table">
    <thead>
      <tr>
        <th>Content</th>
        <th>Status</th>
        <th>Deadline</th>
        <th>Creation Time</th>
        <th>Tags</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for task in task_list %}
        <tr>
          <td>{{ task.content }}</td>
          <td>
            {% if task.status %}
              <span style="color: green">Done</span>
            {% else %}
              <span style="color: red">Not done</span>
            {% endif %}
          </td>
          <td>{{ task.deadline }}</td>
          <td>{{ task.datetime }}</td>
          <td>
            {% for tag in task.tag.all %}
              {{ tag.name }}
            {% empty %}
              <em>No tags</em>
            {% endfor %}
          </td>
          <td>
            <a href="{% url 'todo:task-update' pk=task.id %}" class="btn btn-secondary link-to-page">Update</a>
            <a href="{% url 'todo:task-delete' pk=task.id %}" class="btn btn-danger link-to-page">Delete</a>
            {% if task.status %}
              <form method="post" action="{% url 'todo:task-toggle-assign' pk=task.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-info">Undo</button>
              </form>
            {% else %}
              <form method="post" action="{% url 'todo:task-toggle-assign' pk=task.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Complete</button>
              </form>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}